package com.thedal.thedal_app.voter.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class VoterMongoDTO {
    private String id;
    private String voterId;
    private Long religionId;
    private Long casteId;
    private Long subCasteId;
    private String photoUrl;
    private Long accountId;
    private Long electionId;
    private Integer boothNumber;
    private Boolean hasVoted;
    private LocalDateTime votedTimestamp;
    private LocalDateTime createdTime;
    private LocalDateTime modifiedTime;
    private Integer partNo;
    private Integer sectionNo;
    private Long serialNo;
    private String houseNoEn;
    private String houseNoL1;
    private String houseNoL2;
    private String voterFnameEn;
    private String voterLnameEn;
    private String voterFnameL1;
    private String voterFnameL2;
    private String voterLnameL1;
    private String voterLnameL2;
    private String rlnType;
    private String rlnFnameEn;
    private String rlnLnameEn;
    private String rlnFnameL1;
    private String rlnFnameL2;
    private String rlnLnameL1;
    private String rlnLnameL2;
    private String epicNumber;
    private String gender;
    private String sectionNameEn;
    private String sectionNameL1;
    private String sectionNameL2;
    private String fullAddress;
    private String partNameEn;
    private String partNameL1;
    private String partNameL2;
    private String pincode;
    private Double partLati;
    private Double partLong;
    private Integer age;
    private LocalDate dob;
    private String mobileNo;
    private String whatsappNo;
    private String eMail;
    private Double voterLati;
    private Double voterLongi;
    private String stateCode;
    private String stateNameEn;
    private String stateNameL1;
    private String stateNameL2;
    private String districtCode;
    private String districtNameEn;
    private String districtNameL1;
    private String districtNameL2;
    private String pcNo;
    private String pcNameEn;
    private String pcNameL1;
    private String pcNameL2;
    private String acNo;
    private String acNameEn;
    private String acNameL1;
    private String acNameL2;
    private String urbanNo;
    private String urbanNameEn;
    private String urbanNameL1;
    private Integer urbanWardNo;
    private String rurDistrictUnionNo;
    private String rurDistrictUnionNameEn;
    private String rurDistrictUnionNameL1;
    private String rurDistrictUnionNameL2;
    private String rurDistrictUnionWardNo;
    private String panUnionNo;
    private String panUnionNameEn;
    private String panUnionNameL1;
    private String panUnionNameL2;
    private String panUnionWardNo;
    private String villPanNo;
    private String villPanNameEn;
    private String villPanNameL1;
    private String villPanWardNo;
    private String availability;
    private String partyAffiliation;
    private Boolean starNumber;
    private String aadhaarNumber;
    private String panNumber;
    private String partyRegistrationNumber;
    private Map<String, String> dynamicFields;
    private UUID familyId;
    private Integer familyCount;
    private Set<Long> languageIds;
    private List<Long> benefitSchemeIds;
    private String scheme;
    private Long availabilityId;
    private Long partyId;
    private Integer pageNumber;
    private String remarks;
    private String videoUrl;
    private String otp;
    private LocalDateTime otpCreatedAt;
    private Boolean mobileVerified;
    private Boolean aadhaarVerified;
    private Boolean memberVerified;
    private List<Long> feedbackIssueIds;
    private List<Long> voterHistoryIds;
    private Long partManagerId;
}
