package com.thedal.thedal_app.thedal_exception;

import java.util.LinkedHashMap;
import java.util.Map;

public enum ThedalError {
    INTERNAL_SERVER_ERROR(50000, "Internal Server Error"),
	VOTER_LOCATIONS_FILE_NOT_FOUND(404, "Voter locations file not found for the specified election"),
    INVALID_USER_ROLE(40301, "Ivalid User Role"),
	USER_ALREADY_EXISTS(40302, "User Already Exists"),
	INVALID_VERIFICATION_TOKEN(40303, "Invalid verification token"),
	ROLE_ALREADY_EXISTS(40304, "Role already exists"),
	ACCESS_DENIED(40305, "Access Denied"),
	USER_NOT_FOUND(40306, "User not found"),
	NOT_LOGGED_IN(40307, "Not Logged in"),
	USERNAME_EMPTY(40308, "User name cannot be empty"),
	EMAIL_NOT_FOUND(40309, "Email id not found"),
	INVALID_CREDENTIALS(40310, "invalid username/password"),
	INVALID_USERNAME_FORMAT(40311, "invalid username format"),
	FIRST_NAME_EMPTY(40312, "First name cannot be empty"),
	FIRST_NAME_INVALID(40313, "First name invalid"),
	FIELD_BLANK(40314, "This field must not be blank"),
	INVALID_PASSWORD(40315,
			"Password must be 8 to 15 characters long and include at least one uppercase letter, one lowercase letter, one digit, one special character, and no spaces"),
	EMAIL_REQUIRED(40316, "Email is required"),
	INVALID_EMAIL(40317, "Please Provide a Valid email address"),
	LAST_NAME_INVALID(40318, "Last name invalid"),
	PHONE_NUMBER_EMPTY(40319, "phone number must not be blank"),
	INVALID_MOBILE_NUMBER(40320, "Please enter a valid mobile number"),
	ACCOUNT_NOT_ACTIVE(40321, "User Account not active"),
	ALREADY_REGISTERED(40322, "Already Registered"),
	INVALID_STATUS(40323, "No such status"),
	OTP_EXPIRED(40324, "OTP has expired"),
	INVALID_OTP(40325, "Invalid or expired OTP"),
	PASSWORDS_DO_NOT_MATCH(40326, "Passwords do not match"),
	IMAGE_NOT_FOUND(40327, "Image not found"),
	COLLEGE_ID_NOT_EXISTS(40328, "College ID not exists"),
	INVALID_SUPPORT_DOC_ID(40329, "Invalid Student Support Document id"),
	INVALID_ADMISSION_DOC_ID(40330, "Invalid Student Admission Document id"),
	INVALID_FINAL_DOC_ID(40331, "Invalid Student final Document id"),
	NOTIFICATION_TEMPLATE_NOT_FOUND(40332, "Notification Tempate not found"),
	QUESTION_ID_NOT_FOUND(40333, "Question not found"),
	ANSWER_ID_NOT_FOUND(40334, "Answer not found"),
	QUESTION_CANNOT_EDIT(40335, "Question cannot be edited now"),
	ANSWER_CANNOT_EDIT(40336, "Answer cannot be edited now"),
	NO_ACCESS_EDIT(40337, "No access to edit here"),
	NO_ACCESS_DELETE(40338, "No access to delete here"),
	QUESTION_LIST_EMPTY(40339, "Question List is empty"),
	ANSWER_LIST_EMPTY(40340, "Answer List is empty"),
	JOB_LIST_EMPTY(40341, "Job List is empty"),
	EMPTY_FIELD(40350,"Mandatory field should be filled"),
	PASSWORD_LENGTH_MIN(40351,"Password must be at least 8 characters long"),
	INVALID_PHONE_NUMBER(40352,"Mobile number must be a 10-digit number"),
	/////////////////////////////////////
	



	DUPLICATE_ROLE_FOUND(40100,"Duplicate Role not allowed"),
	ROLE_NOT_FOUND(40101,"No Such Role found"),
	ROLE_NAME_NOT_EMPTY(40102,"Role name cannot be empty"),
	ROLE_PERMISSION_REQUIRED(40103,"User doesn't have the required permission"),
	ROLE_DESCRIPTION_REQUIRED(40104,"Role Description is required"),
	ACCOUNT_STATUS_NOT_FOUND(40105,"status not found"),
	ROLE_PERMISSION_NOT_FOUND(40106,"role permission not found"),
	UNAUTHORIZED_ROLE_EDIT(40107,"Cannot edit these roles"),
	ONBOARD_STATUS_NOT_FOUND(40108,"onboard status not found"),
	ACCOUNT_OR_ONBOARD_STATUS_NOT_FOUND(40109,"Account or onBoardStatus not found."),
	ROLE_NOT_FOUND_OR_UNAUTHORIZED_ROLE_EDIT(40110,"Role not found or Cannot edit these role"),
	
	
	
	
	
	ACCOUNT_ID_NOT_CREATED(40401,"Account not created for this account id"), 
	SERVICE_NOT_FOUND(40405,"Service not found"),
	INVALID_LICENSE_KEY(40405,"Invalid License Key or not found"), 
	DUPLICATE_EMAIL(40406,"Duplicate Email is not allowed"),
	DUPLICATE_MOBILE_NUMBER(40407,"Mobile number is already mapped with other cadre"),
	INVALID_PHONE_NUMBER_FORMAT(40408,"Invalid Number number format"),
	INVALID_COUNTRY_CODE(40411, "Invalid Country code"),
	INVALID_MESSAGING_SERVICE(40408,"Invalid messaging service or not found"), 
	SERVICE_ALREADY_EXISTS(40409,"SMS messaging service are already existed"),
	PICTURE_NOT_FOUND(40410,"Profile picture not found by the existing account id"),
	INVALID_REQUEST(40412, "Invalid SMS service request"),
	MULTIPLE_SERVICES_FOUND(40413, "Multiple SMS service found"),
	INVALID_FILE_TYPE(40414, "Invalid file type"),
	FILE_SIZE_EXCEEDED(40415, "File size is exceeded"),
	TEMP_FILE_CREATION_ERROR(40416, "Temporary File size is exceeded"), 
	FILE_WRITE_ERROR(40417, "File write error"),
	PROFILE_NOT_FOUND(40418, "Profile not found"),
	ACCOUNT_DELETE_FAILED(40419,"Deleting existing election details failed"),
	

	ELECTION_NOT_FOUND(40301, "Election not found"),
	ELECTION_SAVE_FAILED(40302, "Saving election details failed"),
	ELECTION_UPDATE_FAILED(40303, "Updating existing election details failed"),
	ELECTION_DELETE_FAILED(40304, "Deleting existing election details failed"),
	ELECTION_NAME_NOT_FOUND(40305, "Election name cannot be null or empty"),
	ELECTION_TYPE_NOT_FOUND(40305, "Election type id not found"),
	BOOTH_NUMBER_ALREADY_EXISTS(40306,"The booth number already exists."),
	IMAGE_TYPE_NOT_SUPPORTED(40342,"PNG,GIF,JPEG,JPG only supported"),
	IMAGE_SIZE_LIMIT(40343,"Image size limit is 2MB"),
	FILE_NOT_FOUND(40344,"File not found"),
	ELECTION_FETCH_FAILED(40345,"Failed to election details"),
	ELECTION_ID_GREATER_THAN_ZERO(40346,"Election id should be greater than zero"),
	
	MISSING_REQUIRED_FIELD(40701,"Organization name is required for profiles"),
	
	VOTER_NOT_FOUND(40501, "Voter not found"),
	VOTER_SAVE_FAILED(40502, "Saving voter details are failed"),
	VOTER_UPDATE_FAILED(40503, "Updating existing voter details are failed"),
	VOTER_LOCATIONS_RETRIEVAL_FAILED(40504, "Retrieving voter locations are failed"),
	VOTER_LOCATIONS_BOOTH_NUMBER(40515, "Enter correct booth number for voter locations"),
	VOTER_LOCATIONS_ELECTION_ID(40516, "Enter correct election id for voter locations"),
	VOTER_DELETE_FAILED(40514, "Voter deleting failed"),
	//INTERNAL_SERVER_ERROR(40504, "Retrieving voters from third party api error"),
	VOTER_RETRIEVAL_FAILED(40504, "Retrieving voters from third party api error"),
	CSV_PROCESSING_FAILED(40505, "Bulk voters creation failed, check csv file"),
	BOOTH_NOT_FOUND(40506, "Booth not found"),
	VOTER_DATA_INCOMPLETE(40507, "Voter data incomplete"),
	FILE_PROCESSING_FAILED(40508, "File processing for Voter data failed"),
	INVALID_FILE_FORMAT(40509, "Invalid file format for Voter data only accepts .xlsx or csv files"),
	INVALID_SECTION_FILE_FORMAT(40509, "Invalid file format for Section data only accepts .xlsx or csv files"),
	INVALID_PARTMANAGER_FILE_FORMAT(40509, "Invalid file format for Part manager data only accepts .xlsx or csv files"),
	UNKNOWN_ERROR(40510, "An unexpected error occurred"),
	XLSX_PROCESSING_FAILED(40511, "Bulk voters creation failed, check xlsx file"),
	NO_DATA_IN_FILE(40512, "No data in file"),
	INVALID_INPUT(40513, "Enter correct voterId"),
	BULK_UPLOAD_NOT_FOUND(40514, "Bulk upload details are not found"),
	BULK_UPLOAD_NOT_FOUND_ELECTION(40522, "Bulk upload details are not found election id"),
	BULK_UPLOAD_FAILED(40515, "Bulk upload operation failed"),
	BULK_UPLOAD_STARTED(40516, "Bulk upload operation started successfully"),
	BOOTH_NUMBER_NOT_FOUND(40517, "Booth number not found in the uploaded file"),
	ELECTION_BOOTH_SAVE_FAILED(40518, "election booth number save failed"),
	VOTER_DUPLICATE_IN_ELECTIONS(40519, "same voter_id found in multiple elections"),
	INVALID_SORT_PARAMETER(40520, "enter valid id or startTime"),
	DUPLICATE_BOOTH_NUMBERS(40521, "Duplicate booth numbers are not allowed"),
	DATA_INTEGRITY_VIOLATION(40522, "saving voter details are failed database constraint issues"),
	MISSING_REQUIRED_FIELDS(40523, "missing required fields"),
	ELECTION_BOOTH_NOT_FOUND(40524, "missing election booth"),
	ALREADY_VOTED(40525, "Requested voter id is already voted"),
	DUPLICATE_EPIC_NUMBER(40526, "Duplicate EPIC number detected"),
	VOTER_LASTNAME_NOT_FOUND(60787, "Search for valid voter last_name"),

	
	VOLUNTEER_SAVE_FAILED(40601, "Volunteer creation is failed"),
	VOLUNTEER_NOT_FOUND(40602,"Volunteer not found"), 
	VOLUNTEER_UPDATE_FAILED(40603,"Updating volunteer details are failed"),
	VOLUNTEER_DELETE_FAILED(40604,"Deleting volunteer failed"), 
	BULK_ADD_FAILED(40605,"Adding bulk volunteers are failed"), 
	FILE_EMPTY(40606,"Adding bulk volunteers file is empty"), 
	TRACKING_DATA_FETCH_FAILED(40607,"Failed fetch volunteers activities"),
	ACTIVITY_CREATION_FAILED(40608,"Activity creation failed"), 
	ALREADY_CHECKEDIN(40609,"Already checked in"),
	NOT_CHECKEDIN(40610,"Please check in before check out"),
	LATITUDE_MIN(40611,"Latitude must be between -90.0 and 90.0"),
	LATITUDE_MAX(40612,"Latitude must be between -90.0 and 90.0"),
	LONGITUDE_MIN(40613,"Longitude must be between -180.0 and 180.0"),
	LONGITUDE_MAX(40614,"Longitude must be between -180.0 and 180.0"),
	UNAUTHORIZED_ACCESS(40615,"AccountId not matched for deleting volunteer"), 
	VOLUNTEER_ALREADY_ADDED(40616,"Volunteer already added"),
	VOLUNTEER_NOT_IN_ELECTION(40617,"Volunter Not in the Election"),
	
	RELIGION_NOT_FOUND(40650,"Religion id not found"), 
	CASTE_NOT_FOUND(40651,"Caste id not found"),
	SUBCASTE_NOT_FOUND(40652,"SubCaste id not found"),
	RELIGION_UPDATE_FAILED(40653,"Religion Update failed"), 

	BOOTH_SAVE_FAILED(40700,"Saving booths are failed"),
	BOOTH_FETCH_FAILED(40701,"Fetching booth lists failed or enter correct details"), 
	BOOTH_DELETE_FAILED(40702,"Deleting booths are failed"), 
	ELECTION_TYPE_CANNOT_BE_NULL_OR_EMPTY(40703,"Election Type can not be null"),
	PARTY_NAME_NOT_FOUND(40704,"Party name not found"), 
	PARTY_NOT_FOUND(40705,"Party id not found"),
	INVALID_IMAGE_FORMAT(40708,"Invalid PartyImage format"),
	BOOTH_VULNERABILITY_NAME_NOT_FOUND(40706,"Booth Voulnerability name not found"),
	BOOTH_VULNERABILITY_NOT_FOUND(40707,"Booth Voulnerability not found"),
	DYNAMIC_FIELD_NOT_FOUND(40708,"Dynamic field not found"), 
	DYNAMIC_FIELD_MAPPING_ERROR(40709,"Dynamic field mapping error"), 
	ELECTION_TYPES_NOT_FOUND(40710,"Election types are not found"),
	VULNERABILITY_NOT_FOUND(40711,"Booth vulnerability not found"),
	USER_ACCOUNT_MISMATCH(40711,"UserId and accountId are not matching"),
	NO_AVAILABLE_COLUMNS(40712,"Dynamic columns are not available"),
	DUPLICATE_DYNAMIC_FIELD(40713,"Duplicate dynamic fields are found"), 
	ELECTION_ID_NOT_FOUND(40714,"Enter correct Election id is mandatory for creating parties"),
	ELECTION_ALREADY_DELETED(40715,"Election already deleted for these electionId"),
	INVALID_ELECTION_TYPE_ID(40716,"Deleting election_type id is not valid"),
	BOOTH_NOT_FOUND_FOR_ELECTION(40716,"Booth not found for the election or enter correct electionId and boothNumber"),
	UPLOAD_FAILED(40717,"Upload party image is failed"),
	DUPLICATE_PARTY_NAME(40718,"party name is exists"),
	DUPLICATE_VOTER(40719,"Duplicate voter found when saving the voter details"),
	IMAGE_UPLOAD_FAILED(40720,"Failed to upload image"),
	INVALID_IMAGE_SIZE(40721,"Failed to upload image"),
	RELIGIONS_NOT_FOUND(40722,"No religions were found for these account"),
	CASTES_NOT_FOUND(40723,"No castes were found for these account"),
    SUBCASTES_NOT_FOUND(40724,"No sub_castes were found for these account"),
    TOO_MANY_DYNAMIC_FIELDS(40725,"For creating voter we can not give more that 50 dynamic fields"),
    BOOTH_SLIP_PRINT_FAILED(40726,"Booth slip print failed"),
    BOOTH_DELETION_FAILED(40727,"Booth deletion is failed enter correct details"),
    INVALID_BOOTH_ID(40728,"Booth Id is invalid enter correct boothId"),
    RELIGION_LINKED_TO_VOTERS(40729,"Cannot delete religion as it is linked to voters"),
    CASTE_LINKED_TO_VOTERS(40730,"Cannot delete caste as it is linked to voters"),
    SUBCASTE_LINKED_TO_VOTERS(40731,"Cannot delete sub-caste as it is linked to voters"),
    FAMILY_MAPPING_NOT_FOUND(40732,"Related family mapped voters details are not found"),
    INVALID_ASSIGNED_BOOTHS(40733,"Assigned booths are not valid"),
    ALREADY_USED_EMAIL(40734,"Email already in use"),
    ALREADY_USED_MOBILE_NUMBER(40735,"Mobile number already already in use"),
    DUPLICATE_RELIGION(40736,"Religion name exists"),
    DUPLICATE_CASTE(40737,"Caste with name exists for this religion"),
    DUPLICATE_SUB_CASTE(40738,"SubCaste with the same name exists in religion and caste"),
    INVALID_ID_FORMAT(40739,"Invalid voter id"),
    VOTER_ALREADY_MAPPED(40740,"Voter is already mapped to a another family"),
    NO_PERMISSION(40741,"Cadre has no permission to access the election"),
    UNEXPECTED_ERROR(40742,"Unexpected error during volunteer lookup"),
    INVALID_BOOTH_NUMBER_FORMAT(40743,"Booth number format is not ok"),
    INVALID_ELECTION_BODY(40744,"Election body is not valid use only ElectionBody enum values"),
    INVALID_ELECTION_CATEGORY(40745,"Election category is not valid use only POLITICAL or NON_POLITICAL"),
    UNAUTHORIZED_VOLUNTEER_ACCESS(40746,"Unauthorized volunteer access. Volunteer status is inactive"),
    BOOTH_SLIP_NOT_FOUND(40746,"Booth slips are not found"),
    BOOTH_ALREADY_EXISTS(40747,"Booth already exists for the given election and account"),
	TEMPLATE_NOT_FOUND(40748,"Template not found"),
	FILE_TOO_LARGE(40748,"File size exceeds the allowed limit"),
	INVALID_FILE_HEADERS(40749,"Headers are matched the uploaded voter file"),
	FAMILY_ID_MISMATCH(40750,"Family ID mismatch for voter"),
	FAMILY_ID_NOT_FOUND(40751,"Family ID not found for voter"),
	FAMILY_ID_ALREADY_EXISTS(40752,"Family ID is already exists we can not create new familyId"),
	FAMILY_MERGE_FAILED(40753,"Failed to merge family IDs due to database error"),

	BENEFITSCHEME_NOT_FOUND(50741,"Benefitscheme not found"),
	INVALID_SCHEME_BY(50742,"Invalid 'schemeBy' value provided. Please provide a valid value such as 'UNION_GOVT', 'STATE_GOVT','LOCAL_BODY','PARTY','SELF'."),

	AVAILABILITY_NOT_FOUND(60741,"Availability not found"),
	
	LANGUAGE_NOT_FOUND(60748,"Language not found"),

	NOT_VOTED_YET(60744,"Voter not Voted yet"),
	VOTER_ALREADY_VOTED(60745,"Voter has already been marked as voted"),
	VOTER_ALREADY_MARKED_AS_NOT_VOTED(60746,"Voter has already been marked as not voted"),
	
	AVAILABILITY_ALREADY_EXIT(60742,"Availability with the same description already exists."),
    LANGUAGE_ALREADY_EXITS(60747,"language name exists"),
	INVALID_JSON_FORMAT(60743,"Invalid JSON format for updating roles"), 
	BENEFIT_SCHEME_LINKED_TO_VOTER(60748, "Benifit schema linked to voter"),
	AVAILABILITY_LINKED_TO_VOTER(60748,"Availability is linked to voter we cannot delete these availability"),
	INVALID_IMAGE_DIMENSIONS(60749,"Invalid image Dimensions"),
	AVAILABILITY_ALREADY_EXIST(60750,"availablity already exist"),

	//INVALID_JSON_FORMAT(60743,"Invalid JSON format for updating roles"),
	TEMPLATE_NAME_ALREADY_EXISTS(60771,"A template with the same template name already exists for this election and account"),
	INVALID_TEMPLATE_ID(60772,"Invalid template Id, use template Id's only 1,2,3,4"),
	 DUPLICATE_AVAILABILITY(60773,"Availability already exists"),
	USER_INACTIVE(60774,"User status is inactive. Access denied"),
	TEMPLATE_ID_ALREADY_EXISTS(60775,"A template with the same template id already exists for this election and account"),
	ORDER_INDEX_NOT_SET(60776,"Index is not set properly"),
	VOTER_FIRSTNAME_NOT_FOUND(60777,"Search for valid voter first_name"),
	BOOTH_ORDER_UPDATE_FAILED(60778,"Failed to update booth order"),
	LANGUAGE_ORDER_UPDATE_FAILED(60779,"Failed to update language order"),
	AVAILABILITY_ORDER_UPDATE_FAILED(60780,"Failed to update Availability order"),
	BENEFITSCHEME_ORDER_UPDATE_FAILED(60781,"Failed to update BenefitScheme order"), 
	JOB_NOT_FOUND(60782,"JobId not found for these election"),
	EXPORT_FAILED(60783,"File export failed to Aws"),
	TEMPLATE_ORDER_UPDATE_FAILED(60784,"Failed to update BenefitScheme order"),
	PARTY_ORDER_UPDATE_FAILED(60785,"Failed to update Party order"),
	BANNER_ORDER_UPDATE_FAILED(60786,"Failed to update Banner order"),

	Part_Number_ALREADY_EXISTS(70101,"Part Number already exists"),
	PARTMANAGER_NOT_FOUND(70102,"Part Manager not found"),
	PARTMANAGER_LINKED_TO_VOTER(70103,"Part Manager cannot be deleted as it is linked to voters"),
	FILE_PROCESSING_ERROR(70104,"Error processing CSV file"),

	SECTION_ALREADY_EXISTS(70105,"Section alredy exists"),
	SECTION_NOT_SAVED(70106,"Section not saved"),
	SECTION_NOT_FOUND(70107,"Section not found"),
	EXCEEDS_VOTER_LIMIT(70108,"Requested limit exceeds available voters"),
	FILE_NOT_READY(70109,"Download file not completed"),
	VOTER_LIMIT_EXCEEDED(70110,"Requested number of voters exceeds available voters"),
	INVALID_FILE_DATA(70111,"Invalid voter file data, please check mandatory fields"),
	MANDATORY_FIELDS_MISSING(70112,"Missing mandatory columns from file, please check mandatory fields"),
	ALL_RECORDS_FAILED(70113,"All records in the file failed validation"),
	MISMATCHED_INPUT(70114,"Mismatch input values"),
	INVALID_CREQUEST(70115,"Invalid electionId. Control panel requests must use electionId = 0"),

	ROLE_CANNOT_BE_DELETED_DUE_TO_DEPENDENCIES(70117,"Role cannot be deleted because it is still assigned to users"),

	INVALID_PARTY_ID(70116,"Invalid Party Id"),
	SCHEME_ALREADY_EXISTS(70117,"Scheme already exists"),
	RELIGION_ID_REQUIRED(70118,"ReligionId is required when we want to create caste"),
	ALL_ROWS_FAILED(70119,"Cadre bulk upload failed"),
	INVALID_SORT_FIELD(70120,"Invalid sort field for get bulk upload"),
	INVALID_GENDER(70121,"Provide valid gender(male, female, other)"),
	INVALID_AGE_RANGE(70122,"Provide valid age(min 18)"),
	EPIC_NUMBER_ALREADY_EXISTS(70123,"Epic number already exists in these election and account"),
	UNAUTHORIZED_ELECTION_ACCESS(70124,"cadre is not associated with these election"),
	INVALID_ELECTION(70125,"Election does not belong to Current Account"),
	RELIGION_LINKED_TO_CASTE_OR_SUBCASTE(70126,"Cannot delete religion"),
	CASTE_LINKED_TO_SUBCASTE(70127,"Cannot delete caste linked to subcaste"),
	PARTNO_MANDATORY(70128,"PartNo can not empty or null"),
	SCHOOLNAME_MANDATORY(70129,"SchoolName can not empty or null"),
	PINCODE_MANDATORY(70130,"Pincode can not empty or null"),
	SLIP_ID_ALREADY_EXISTS(70131,"Voter Slip already exists"),
	PARTNAMEEG_MANDATORY(70132,"Part name english is mandatory can not empty or null"),
	VOLUNTEER_STATUS(70133,"Volunteer is inactive and not eligible to log in"),
	SCHEDULING_FAILED(70134,"Voter data export failed scheduling"),
	MEMBER_NOT_FOUND(70135,"member not found"), 
	INVALID_DOB(70136,"Invalid hasDob parameter. Must be 'yes'"),
	
	DUPLICATE_ENTRY(70137,"Voter history with this name already exists"), 
	VOTER_HISTORY_NOT_FOUND(70138,"Voter history not found"), 
	VIDEO_UPLOAD_FAILED(70139,"Failed to upload video file"),
	INVALID_VIDEO_SIZE(70140,"Video file size exceeds the maximum limit of 10 MB."), 
	INVALID_VIDEO_FORMAT(70141,"Invalid video format. Only MP4, AVI, and MOV are allowed"), 
	AADHAAR_NOT_FOUND(70142,"Aadhar not found"), 
	OTP_REQUEST_FAILED(70143,"OTP request failed"), 
	OTP_VERIFICATION_FAILED(70144,"OTP verification failed"),
	INVALID_AADHAAR_NUMBER(70145,"Invalid aadhar number"),
	INVALID_OTP_OR_REFID(70145,"Invalid OTP or RefId"),
	MOBILE_NUMBER_ALREADY_EXISTS(70146,"mobile no alredy exists"),
	 VOTER_HISTORY_ORDER_UPDATE_FAILED(70147,"Voter history order failed to update"), 
	 INVALID_BANNER_FILE(70148,"Invalid banner file"), 
	 ISSUE_ALREADY_EXISTS(70149,"Feedback or issue already exists"), 
	 ISSUE_NOT_FOUND(70150,"feedback or issue not found"), 
	 AADHAAR_ALREADY_EXISTS(70151,"aadhaar number already exists "),
	 S3_DELETE_FAILED(70152,"delete export failed from s3"), 

	 DUPLICATE_AADHAAR_NUMBER(70153,"A voter with Aadhaar number"),

	 INVALID_SEARCH_QUERY(70152, "Invalid search query"),
	 AVAILABILITY_CATEGORY_ALREADY_EXIST(70154,"Availability with the same category name already exists for this election"),
	 AVAILABILITY_DESCRIPTION_ALREADY_EXIST(70155,"Availability with the same description already exists for this election"),
	 ELECTION_NO_RECORDS(801010,"This election not have any records"), 
	 PARTY_LINKED_TO_VOTER(70156,"Party is linked to voters"),
	 PARTMANAGER_SAVE_FAILED(70157,"creating part and vulnerability is failed for these election"),
	 PARTMANAGER_FETCH_FAILED(70158,"fetching part and vulnerability is failed for these election"),
	 PARTMANAGER_UPDATE_FAILED(70159,"Update part and vulnerability is failed for these election"),
	 INVALID_PART_NO(70160,"Invalid part number"), 
	 INVALID_PAGE_SIZE(70161,"Invalid page size"), 
	 SURVEY_FORM_NOT_FOUND(70162,"Survey form not found"), 
	 INVALID_FORM_FIELDS(70163,"Invalid custom fields. Ensure label, type, and options (for dropdown) are valid"), 
	 INVALID_FORM_STATUS(70164,"Invalid form status. Must be true or false"),
	 DUPLICATE_CATALOGUE_ITEM_NAME(70165,"Catalogue name already existed"),
	 CATALOGUE_ITEM_NOT_FOUND(70166,"Catalogue Item not found"),
	 INVALID_CATALOGUE_ITEM_ID(70167,"Invalid Catalogue Itemid"), 
	 CATALOGUE_ITEM_NAME_NOT_FOUND(70168,"Catalogue Item name not found"),
	 INVALID_PRICE(70169,"Invalid price"),
	 CATALOGUE_ITEM_DESCRIPTION_NOT_FOUND(70170,"Catalogue Item description not found"),
	 PART_NO_NOT_FOUND(70171,"Part_no not found in voters"), 
	 DEFAULT_TEMPLATE_CANNOT_BE_DELETED(70172,"The default template cannot be deleted"),
	 INVALID_SUBMISSION_DATA(70173,"Invalid submission data provided"), 
	 INVALID_SUBMISSION_DATA_TYPE(70174,"Invalid data type in submission data"), 
	 MISSING_REQUIRED_FIELD_FOR_FORM(70175,"Required field is missing in submission data"),
	 INVALID_SORT_DIRECTION(70176,"Invalid sort direction"), 
	 INVALID_SLIP_BOX_ID(70177,"Invalid slip boxId or not exists in table"), 
	 INVALID_SLIP_BOX_IDS(70178,"Invalid slip boxId's or not exists in table"), 
	 INVALID_FILE(70179,"Invalid uploaded file slip box"), 
	 SLIP_BOX_NOT_FOUND(70180,"slip box not found for cpanel"), 
	 SLIP_BOX_ALREADY_EXISTS(70181,"slip box already exists for cpanel"), 
	 SLIP_BOX_IDS_REQUIRED(70182,"No slip box IDs provided for deletion"), 
	 INVALID_PART_NUMBERS(70183,"Invalid part numbers provided\", \"Please provide a non-empty list of valid part numbers"), 
	 CATALOGUE_ITEM_ORDER_UPDATE_FAILED(70184,"Failed to update catalogue item order"), 
	 DEFAULT_SLIP_BOX_DELETION_NOT_ALLOWED(70189,"User cannot delete default slip box"), 
	 SUBMISSIONS_NOT_FOUND(70190,"Survey submissions are not found"), 
	 INVALID_IMAGE_FIELD(70191,"invalid image field"), 
	 INVALID_IMAGE_DATA(70192,"invalid image data"), 
	 SURVEY_FORM_ORDER_UPDATE_FAILED(70193,"SURVEY_FORM_ORDER_UPDATE_FAILED"),
	 SURVEY_FORM_FIELDS_REORDER_FAILED(70194,"Survey form fields reordered failed"), 
	 MONGO_WRITE_FAILED(70195,"Failed to save to MongoDB"), 
	 LANGUAGE_DELETION_FAILED(70196,"unable to delete the languages"), 
	 AVAILABILITY_DELETION_FAILED(70197,"unable to delete the availabilities"), 
	 MONGO_OPERATION_FAILED(70198,"mongodb operation failed"), 
	 AVAILABILITY_ASSOCIATED_WITH_VOTERS(70199,"Availabilities associated with voters"), 
	 VOTER_HISTORY_LINKED_TO_VOTER(70200,"Voter History associated with voters"), 
	 VOTER_HISTORY_DELETION_FAILED(70201,"Unable to delete Voter History"), 
	 DUPLICATE_CASTE_CATEGORY(70202,"Same category already presented"), 
	 CASTE_CATEGORIES_NOT_FOUND(70203,"Caste categories not found"),   
	 CASTE_CATEGORY_NOT_FOUND(70204,"Caste category not found"), 
	 INVALID_IMAGE_STATUS(70205,"Invalid image status, we cannot change image status"),
	 INVALID_ELECTION_ID(70206,"Invalid electionId"), 
	 INVALID_EPIC_NUMBER(70207,"Invalid epic number"),
	 INVALID_PARTY_NAME(70208,"Invalid party name"), 
	 INVALID_FORM_NAME(70209,"Invalid form name for update form"), 
	 SURVEY_FORM_UPDATE_FAILED(70210,"survey form update failed"), 
	 INVALID_FRIEND_MAPPING(70211,"Cannot map a voter as their own friend. epicNumber"), 
	 FRIEND_ID_ALREADY_EXISTS(70212,"Friend ID is already exists we can not create new friendsId"), 
	 FRIEND_MAPPING_ALREADY_EXISTS(70213,"Friends ID is already exists we can not create new friendsId"), 
	 FRIEND_MAPPING_NOT_FOUND(70214,"Friends ID not found"),      
	 
	 DATA_MIGRATION_COMPLETED(70202,"Data migration completed successfully"),
	 DATA_MIGRATION_FAILED(70203,"Data migration failed"),
	 
	 // New migration error codes
	 MIGRATION_JOB_NOT_FOUND(70210, "Migration job not found"),
	 CLEANUP_FAILED(70211, "MongoDB cleanup failed"),
	 VALIDATION_FAILED(70212, "Data validation failed"),
	 STATS_RETRIEVAL_FAILED(70213, "Failed to retrieve migration statistics"),
	 REDIS_CONNECTION_FAILED(70214, "Unable to connect to Redis"), 
	 NO_POLLING_DATA_FOUND(70215, "No polling data found"), 
	 ELECTION_OVERVIEW_NOT_FOUND(70216,"Election overview data not found"),
	 TOTAL_VOTERS_RECORD_NOT_FOUND(70217,"TOTAL_VOTERS record not found"), 
	 NO_DATA_FOUND(70218,"No polling data available for election"), 
	 URL_TOO_LONG(70219,"Presigned URL exceeds maximum length"), 
	 JOB_SCHEDULING_FAILED(70220,"survey export job scheduling is failed"), 
	 MONGO_SYNC_FAILED(70221,"MongoDB sync failed for reorder party"), 
	 INVALID_FRIEND_EPIC_NUMBER(70222,"Invalid friend epic number, please check again"), 
	 FRIEND_NOT_FOUND(70223,"friendId not found for voter"), 
	 FRIEND_DETAILS_SERIALIZATION_FAILED(70224,"Failed to serialize friend details"), 
	
	 FRIEND_DETAILS_NOT_PERSISTED(70224,"Friend details not persisted to database"),
	 DATABASE_SAVE_FAILED(70224,"Failed to save voter to database"), 
	 DATABASE_ERROR(70225,"Failed to sync voter mongo"), 

	 VOTER_MISMATCH(70226,"Voter mismatch between PostgreSQL and MongoDB"), 
	 VOTER_NOT_FOUND_IN_MONGO(70227,"Voter not found MongoDB"), 
	 VOTER_NOT_FOUND_IN_POSTGRES(70228,"Voter not found PostgresDB"), 
	 VOTER_UPSERT_FAILED(70229,"MongoDb upsert failed"), 
	 //+9MONGO_DELETE_FAILED(70230,"Failed to delete mongoDB voters"), 
	 OPERATION_FAILED(70231,"Failed to delete voters"), 
	 PDF_PROCESSING_FAILED(70232,"Failed to process PDF mismatch serialno and images"), 
	 FAMILY_GROUPING_ALREADY_EXECUTED(70233,"Family grouping already executed for this election"), 
	 INVALID_FILE_SIZE(70234,"Invalid file size, it exceeds 5MB"), 
	 INVALID_FILE_FIELD(70235,"Invalid file field it can accept image or file"),  
	 
	 // Family Mapping Job Errors
	 FAMILY_MAPPING_JOB_NOT_FOUND(70226, "Family mapping job not found"),
	 BULK_UPLOAD_IN_PROGRESS(70227, "A bulk upload is already in progress for this election"),
	 MERGE_JOB_IN_PROGRESS(70236, "A merge operation is already in progress for this election"),
	 MERGE_JOB_NOT_FOUND(70237, "Merge job not found"),
	 PARTMANAGER_ORDER_UPDATE_FAILED(70228, "partManager reoder is failed"), 
	 MOBILE_NOT_VERIFIED(70229, "Mobile not verified"), 
	 OTP_SEND_FAILED(70230, "OTP send failed"), 
	 OTP_NOT_REQUIRED(70231, "OTP verification not required for this election"),    
	 OTP_REQUIRED(70232,"OTP verification is required for this election"), 
	 INVALID_FILTER_COMBINATION(70233,"Cannot apply both fatherless and guardian filters simultaneously"), 
	 DATABASE_UPDATE_FAILED(70234,"Failed to update admin_user_id for election_id"), 
	 INVALID_IMAGE_URL(70235,"Invalid image URL format"), 
	 IMAGE_DELETION_FAILED(70236,"Failed to delete image from storage"), 
	 INVALID_NAME_PARAMETER(70237,"Invalid name parameter"),  	
	 MAX_FIELDS_EXCEEDED(70238,"Maximum of 5 dynamic fields allowed per election"),
	 DYNAMIC_FIELD_ORDER_UPDATE_FAILED(70239,"Failed to update dynamic field order"), 
	 INVALID_CASTE_FILE_FORMAT(70240,"Invalid file format for caste upload. Only .xlsx and .csv are supported"), 
	 INVALID_SUBCASTE_FILE_FORMAT(70241,"Invalid file format for sub-caste upload. Only .xlsx and .csv are supported"), 
	 DATABASE_CONSTRAINT_VIOLATION(70242,"DataBase constraint violation while updating dynamic field status"),
	 EXPORT_NOT_READY(70243,"Export job is not ready or still processing"),
	 EXPORT_FILE_NOT_FOUND(70244,"Export file not found"),
	 
	 // Election Freeze/Unfreeze Errors
	 ELECTION_ALREADY_FROZEN(70245,"Election is already frozen"),
	 ELECTION_NOT_FROZEN(70246,"Election is not frozen"),
	 ELECTION_FROZEN(70247,"Cannot perform this operation. Election is frozen and in read-only mode."),
	 
	 
	;

	

    private static final Map<Integer, ThedalError> lookup = new LinkedHashMap<>();

	static {
		for (ThedalError values : ThedalError.values()) {
			lookup.put(values.getCode(), values);
		}
	}

	
	
	private final int code;
	private final String message;

	private ThedalError(int code, String message) {
		this.code = code;
		this.message = message;
	}

	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

	public static ThedalError fromErrorCode(int errorCode) {
		return lookup.get(errorCode);
	}

}


